function [ checkerboard ] = Checkerboard
global S


checkerboard = Checkerboard( ...
    S.PTB.wRect(3) ,...
    S.PTB.wRect(4) ,...
    S.Parameters.Checkerboard.nSquareWidth ,...
    S.Parameters.Checkerboard.FlicColor, ...
    S.Parameters.Checkerboard.FlacColor ...
    );

checkerboard.LinkToWindowPtr( S.PTB.wPtr )

checkerboard.AssertReady % just to check

end % function
